IF NOT EXISTS(SELECT principal_id FROM sys.server_principals WHERE name = '$(MSSQL_ASYALOGIC_USER)') BEGIN
    CREATE LOGIN [$(MSSQL_ASYALOGIC_USER)] WITH PASSWORD = '$(MSSQL_ASYALOGIC_PASS)'
END
GO

IF NOT EXISTS(SELECT principal_id FROM sys.database_principals WHERE name = '$(MSSQL_ASYALOGIC_USER)') BEGIN
    CREATE USER [$(MSSQL_ASYALOGIC_USER)] FOR LOGIN [$(MSSQL_ASYALOGIC_USER)]
    ALTER SERVER ROLE sysadmin ADD MEMBER [$(MSSQL_ASYALOGIC_USER)]
END
GO